<?php
// module/Album/view/album/album/index.phtml:

$title = 'Song';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('song', array('action'=>'add'));?>">Add new song</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($song as $song) : ?>
<tr>
    <td><?php echo $this->escapeHtml($song->title);?></td>
    <td><?php echo $this->escapeHtml($song->artist);?></td>
    <td>
        <a href="<?php echo $this->url('song',
            array('action'=>'edit', 'id' => $song->id));?>">Edit</a>
        <a href="<?php echo $this->url('song',
            array('action'=>'delete', 'id' => $song->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>